version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-25-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
         name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
         command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}

      test:
      override:
      - emulator -avd circleci-android22 -no-audio -no-window:
                           background: true
                           parallel: true

      steps:
      -run:
            name: wait for Boot
            command:   - circle-android wait-for-boot
      -run:
            name: unlock the emulator screen
            command: - sleep 30
       -run:
            name: adb shell input
            command: - adb shell input keyevent 82

      - run:
          name: Run connectedAndroidTest
          command: ./gradlew lint connectedAndroidTest --stacktrace
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results
      # See https://circleci.com/docs/2.0/deployment-integrations/ for deploy example
     # - test:
      #  override:
       #   name: Run Instrumented Test
        #  command: ./gradlew connectedAndroidTest