version: 2
jobs:
  build:
    #test:
      #working_directory: ~/code
      docker:
        - image: circleci/android:api-26-alpha  # gcloud is baked into this image
      environment:
        JVM_OPTS: -Xmx3200m
      steps:
        - checkout
        - restore_cache:
            key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
        - run:
            name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
            command: sudo chmod +x ./gradlew
        - run:
            name: Download Dependencies
            command: ./gradlew androidDependencies

        - save_cache:
            paths:
              - ~/.gradle
            key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}

        - run:
            name: Store Google Service Account
            command: echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json

       # - run:
        #    name: Build debug APK and release APK
         #   command:
          #    ./gradlew :app:assembleDebug
           #   ./gradlew :app:assembleDebugAndroidTest

