version: 2
jobs:
  build:
    #test:
      docker:
        - image: circleci/android:api-28-alpha  # gcloud is baked into this image
      steps:
        - run:
            name: Download Dependencies
            command: ./gradlew androidDependencies
        - run:
            name: Build debug APK and release APK
            command:
              ./gradlew :app:assembleDebug
              ./gradlew :app:assembleDebugAndroidTest
